name: Tina Hammar
favicon: null
layout_spectrum: 0
typography_spectrum: 0.09618
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ded8c8'
    - '#0c1212'
    - '#686e6e'
    - '#94513e'
    - '#849b23'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
