name: Tina Hammar
favicon: null
layout_spectrum: 0
typography_spectrum: 0.09618
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#728029'
    - '#c3cdce'
    - '#cc9869'
  brandStrength: 0.1875
  lightness: 0.9375
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
