name: Tina Hammar
favicon: null
layout_spectrum: 0.7932799980044365
typography_spectrum: 0.55732835480012
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.2623939255718142
  lightness: 0.8103740653023124
  saturation: 0.8503225424792618
  rhythmicContrast: 0.9639560428913683
purpose: []
